# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				hoglin = true
				camel = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				wither_skeleton = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				phantom = true
				ender_dragon = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				cat = true
				zombie = true
				guardian = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				eye_of_ender = true
				wolf = true
				villager = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				polar_bear = true
				strider = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true
				husk = true
				boat = true
				minecart = true
				vindicator = true
				evoker = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true
				skull = true
				jungle_skeleton = true
				naga = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				cubozoa = true
				shadow_walker = true
				end_slime = true
				silk_moth = true
				end_fish = true

			[light_sources.settings.entities.create]
				super_glue = true

			[light_sources.settings.entities.cobblemon]
				empty_pokeball = true
				pokemon = true

			[light_sources.settings.entities.supplementaries]
				rope_arrow = true

			[light_sources.settings.entities.mcwfurnitures]
				chair_entity = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

