version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = false
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 128
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = true
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
mcwfences = true
farmersdelight = true
bountiful = true
mcwroofs = true
mcwwindows = true
betternether = true
betterend = true
ends_delight = true
chalk = true
mcwpaths = true
create_enchantment_industry = true
bellsandwhistles = true
mcwbridges = true
railways = true
mcwtrpdoors = true
mcwlights = true
milk = true
mcda = true
amendments = true
mcwholidays = true
handcrafted = true
snowrealmagic = true
cobblemon = true
extendedgears = true
create_cobblemon = true
spell_engine = true
creategoggles = true
mcwdoors = true
supplementaries = true
createbigcannons = true
chipped = true
create = true
sawmill = true
culturaldelights = true
minecraft = true
create_jetpack = true
createdeco = true
betterarcheology = true
mcwfurnitures = true
travelersbackpack = true
createaddition = true
jewelry = true
beautify = true
sliceanddice = true
decorative_blocks = true
archers = true
expandeddelight = true
toms_storage = true
